// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../../../android/net/ConnectivityManager.dart' as connectivitymanager$_;

import '../../../android/net/LinkProperties.dart' as linkproperties$_;

import '../../../android/net/Network.dart' as network$_;

import '../../../android/net/NetworkCapabilities.dart' as networkcapabilities$_;

/// from: `dev.zeekr.connectivity_manager.JConnectivityManager$JNetworkCallback`
class JConnectivityManager$JNetworkCallback extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<JConnectivityManager$JNetworkCallback> $type;

  @jni$_.internal
  JConnectivityManager$JNetworkCallback.fromReference(
    jni$_.JReference reference,
  ) : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/connectivity_manager/JConnectivityManager$JNetworkCallback',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JConnectivityManager$JNetworkCallback?>
  nullableType = $JConnectivityManager$JNetworkCallback$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JConnectivityManager$JNetworkCallback> type =
      $JConnectivityManager$JNetworkCallback$Type$();
  static final _id_onAvailable = _class.instanceMethodId(
    r'onAvailable',
    r'(Landroid/net/Network;)V',
  );

  static final _onAvailable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onAvailable(network: android.net.Network): kotlin.Unit`
  void onAvailable(network$_.Network network) {
    final _$network = network.reference;
    _onAvailable(
      reference.pointer,
      _id_onAvailable as jni$_.JMethodIDPtr,
      _$network.pointer,
    ).check();
  }

  static final _id_onBlockedStatusChanged = _class.instanceMethodId(
    r'onBlockedStatusChanged',
    r'(Landroid/net/Network;Z)V',
  );

  static final _onBlockedStatusChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public fun onBlockedStatusChanged(network: android.net.Network, blocked: kotlin.Boolean): kotlin.Unit`
  void onBlockedStatusChanged(network$_.Network network, bool z) {
    final _$network = network.reference;
    _onBlockedStatusChanged(
      reference.pointer,
      _id_onBlockedStatusChanged as jni$_.JMethodIDPtr,
      _$network.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_onCapabilitiesChanged = _class.instanceMethodId(
    r'onCapabilitiesChanged',
    r'(Landroid/net/Network;Landroid/net/NetworkCapabilities;)V',
  );

  static final _onCapabilitiesChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onCapabilitiesChanged(network: android.net.Network, networkCapabilities: android.net.NetworkCapabilities): kotlin.Unit`
  void onCapabilitiesChanged(
    network$_.Network network,
    networkcapabilities$_.NetworkCapabilities networkCapabilities,
  ) {
    final _$network = network.reference;
    final _$networkCapabilities = networkCapabilities.reference;
    _onCapabilitiesChanged(
      reference.pointer,
      _id_onCapabilitiesChanged as jni$_.JMethodIDPtr,
      _$network.pointer,
      _$networkCapabilities.pointer,
    ).check();
  }

  static final _id_onLinkPropertiesChanged = _class.instanceMethodId(
    r'onLinkPropertiesChanged',
    r'(Landroid/net/Network;Landroid/net/LinkProperties;)V',
  );

  static final _onLinkPropertiesChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onLinkPropertiesChanged(network: android.net.Network, linkProperties: android.net.LinkProperties): kotlin.Unit`
  void onLinkPropertiesChanged(
    network$_.Network network,
    linkproperties$_.LinkProperties linkProperties,
  ) {
    final _$network = network.reference;
    final _$linkProperties = linkProperties.reference;
    _onLinkPropertiesChanged(
      reference.pointer,
      _id_onLinkPropertiesChanged as jni$_.JMethodIDPtr,
      _$network.pointer,
      _$linkProperties.pointer,
    ).check();
  }

  static final _id_onLosing = _class.instanceMethodId(
    r'onLosing',
    r'(Landroid/net/Network;I)V',
  );

  static final _onLosing =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public fun onLosing(network: android.net.Network, maxMsToLive: kotlin.Int): kotlin.Unit`
  void onLosing(network$_.Network network, int i) {
    final _$network = network.reference;
    _onLosing(
      reference.pointer,
      _id_onLosing as jni$_.JMethodIDPtr,
      _$network.pointer,
      i,
    ).check();
  }

  static final _id_onLost = _class.instanceMethodId(
    r'onLost',
    r'(Landroid/net/Network;)V',
  );

  static final _onLost =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onLost(network: android.net.Network): kotlin.Unit`
  void onLost(network$_.Network network) {
    final _$network = network.reference;
    _onLost(
      reference.pointer,
      _id_onLost as jni$_.JMethodIDPtr,
      _$network.pointer,
    ).check();
  }

  static final _id_onReserved = _class.instanceMethodId(
    r'onReserved',
    r'(Landroid/net/NetworkCapabilities;)V',
  );

  static final _onReserved =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onReserved(networkCapabilities: android.net.NetworkCapabilities): kotlin.Unit`
  void onReserved(
    networkcapabilities$_.NetworkCapabilities networkCapabilities,
  ) {
    final _$networkCapabilities = networkCapabilities.reference;
    _onReserved(
      reference.pointer,
      _id_onReserved as jni$_.JMethodIDPtr,
      _$networkCapabilities.pointer,
    ).check();
  }

  static final _id_onUnavailable = _class.instanceMethodId(
    r'onUnavailable',
    r'()V',
  );

  static final _onUnavailable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun onUnavailable(): kotlin.Unit`
  void onUnavailable() {
    _onUnavailable(
      reference.pointer,
      _id_onUnavailable as jni$_.JMethodIDPtr,
    ).check();
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $JConnectivityManager$JNetworkCallback> _$impls =
      {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onAvailable(Landroid/net/Network;)V') {
        _$impls[$p]!.onAvailable(
          $a![0]!.as(const network$_.$Network$Type$(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'onBlockedStatusChanged(Landroid/net/Network;Z)V') {
        _$impls[$p]!.onBlockedStatusChanged(
          $a![0]!.as(const network$_.$Network$Type$(), releaseOriginal: true),
          $a![1]!
              .as(const jni$_.$JBoolean$Type$(), releaseOriginal: true)
              .booleanValue(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d ==
          r'onCapabilitiesChanged(Landroid/net/Network;Landroid/net/NetworkCapabilities;)V') {
        _$impls[$p]!.onCapabilitiesChanged(
          $a![0]!.as(const network$_.$Network$Type$(), releaseOriginal: true),
          $a![1]!.as(
            const networkcapabilities$_.$NetworkCapabilities$Type$(),
            releaseOriginal: true,
          ),
        );
        return jni$_.nullptr;
      }
      if ($d ==
          r'onLinkPropertiesChanged(Landroid/net/Network;Landroid/net/LinkProperties;)V') {
        _$impls[$p]!.onLinkPropertiesChanged(
          $a![0]!.as(const network$_.$Network$Type$(), releaseOriginal: true),
          $a![1]!.as(
            const linkproperties$_.$LinkProperties$Type$(),
            releaseOriginal: true,
          ),
        );
        return jni$_.nullptr;
      }
      if ($d == r'onLosing(Landroid/net/Network;I)V') {
        _$impls[$p]!.onLosing(
          $a![0]!.as(const network$_.$Network$Type$(), releaseOriginal: true),
          $a![1]!
              .as(const jni$_.$JInteger$Type$(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'onLost(Landroid/net/Network;)V') {
        _$impls[$p]!.onLost(
          $a![0]!.as(const network$_.$Network$Type$(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'onReserved(Landroid/net/NetworkCapabilities;)V') {
        _$impls[$p]!.onReserved(
          $a![0]!.as(
            const networkcapabilities$_.$NetworkCapabilities$Type$(),
            releaseOriginal: true,
          ),
        );
        return jni$_.nullptr;
      }
      if ($d == r'onUnavailable()V') {
        _$impls[$p]!.onUnavailable();
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $JConnectivityManager$JNetworkCallback $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'dev.zeekr.connectivity_manager.JConnectivityManager$JNetworkCallback',
      $p,
      _$invokePointer,
      [
        if ($impl.onAvailable$async) r'onAvailable(Landroid/net/Network;)V',
        if ($impl.onBlockedStatusChanged$async)
          r'onBlockedStatusChanged(Landroid/net/Network;Z)V',
        if ($impl.onCapabilitiesChanged$async)
          r'onCapabilitiesChanged(Landroid/net/Network;Landroid/net/NetworkCapabilities;)V',
        if ($impl.onLinkPropertiesChanged$async)
          r'onLinkPropertiesChanged(Landroid/net/Network;Landroid/net/LinkProperties;)V',
        if ($impl.onLosing$async) r'onLosing(Landroid/net/Network;I)V',
        if ($impl.onLost$async) r'onLost(Landroid/net/Network;)V',
        if ($impl.onReserved$async)
          r'onReserved(Landroid/net/NetworkCapabilities;)V',
        if ($impl.onUnavailable$async) r'onUnavailable()V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory JConnectivityManager$JNetworkCallback.implement(
    $JConnectivityManager$JNetworkCallback $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return JConnectivityManager$JNetworkCallback.fromReference(
      $i.implementReference(),
    );
  }
}

abstract base mixin class $JConnectivityManager$JNetworkCallback {
  factory $JConnectivityManager$JNetworkCallback({
    required void Function(network$_.Network network) onAvailable,
    bool onAvailable$async,
    required void Function(network$_.Network network, bool z)
    onBlockedStatusChanged,
    bool onBlockedStatusChanged$async,
    required void Function(
      network$_.Network network,
      networkcapabilities$_.NetworkCapabilities networkCapabilities,
    )
    onCapabilitiesChanged,
    bool onCapabilitiesChanged$async,
    required void Function(
      network$_.Network network,
      linkproperties$_.LinkProperties linkProperties,
    )
    onLinkPropertiesChanged,
    bool onLinkPropertiesChanged$async,
    required void Function(network$_.Network network, int i) onLosing,
    bool onLosing$async,
    required void Function(network$_.Network network) onLost,
    bool onLost$async,
    required void Function(
      networkcapabilities$_.NetworkCapabilities networkCapabilities,
    )
    onReserved,
    bool onReserved$async,
    required void Function() onUnavailable,
    bool onUnavailable$async,
  }) = _$JConnectivityManager$JNetworkCallback;

  void onAvailable(network$_.Network network);
  bool get onAvailable$async => false;
  void onBlockedStatusChanged(network$_.Network network, bool z);
  bool get onBlockedStatusChanged$async => false;
  void onCapabilitiesChanged(
    network$_.Network network,
    networkcapabilities$_.NetworkCapabilities networkCapabilities,
  );
  bool get onCapabilitiesChanged$async => false;
  void onLinkPropertiesChanged(
    network$_.Network network,
    linkproperties$_.LinkProperties linkProperties,
  );
  bool get onLinkPropertiesChanged$async => false;
  void onLosing(network$_.Network network, int i);
  bool get onLosing$async => false;
  void onLost(network$_.Network network);
  bool get onLost$async => false;
  void onReserved(
    networkcapabilities$_.NetworkCapabilities networkCapabilities,
  );
  bool get onReserved$async => false;
  void onUnavailable();
  bool get onUnavailable$async => false;
}

final class _$JConnectivityManager$JNetworkCallback
    with $JConnectivityManager$JNetworkCallback {
  _$JConnectivityManager$JNetworkCallback({
    required void Function(network$_.Network network) onAvailable,
    this.onAvailable$async = false,
    required void Function(network$_.Network network, bool z)
    onBlockedStatusChanged,
    this.onBlockedStatusChanged$async = false,
    required void Function(
      network$_.Network network,
      networkcapabilities$_.NetworkCapabilities networkCapabilities,
    )
    onCapabilitiesChanged,
    this.onCapabilitiesChanged$async = false,
    required void Function(
      network$_.Network network,
      linkproperties$_.LinkProperties linkProperties,
    )
    onLinkPropertiesChanged,
    this.onLinkPropertiesChanged$async = false,
    required void Function(network$_.Network network, int i) onLosing,
    this.onLosing$async = false,
    required void Function(network$_.Network network) onLost,
    this.onLost$async = false,
    required void Function(
      networkcapabilities$_.NetworkCapabilities networkCapabilities,
    )
    onReserved,
    this.onReserved$async = false,
    required void Function() onUnavailable,
    this.onUnavailable$async = false,
  }) : _onAvailable = onAvailable,
       _onBlockedStatusChanged = onBlockedStatusChanged,
       _onCapabilitiesChanged = onCapabilitiesChanged,
       _onLinkPropertiesChanged = onLinkPropertiesChanged,
       _onLosing = onLosing,
       _onLost = onLost,
       _onReserved = onReserved,
       _onUnavailable = onUnavailable;

  final void Function(network$_.Network network) _onAvailable;
  final bool onAvailable$async;
  final void Function(network$_.Network network, bool z)
  _onBlockedStatusChanged;
  final bool onBlockedStatusChanged$async;
  final void Function(
    network$_.Network network,
    networkcapabilities$_.NetworkCapabilities networkCapabilities,
  )
  _onCapabilitiesChanged;
  final bool onCapabilitiesChanged$async;
  final void Function(
    network$_.Network network,
    linkproperties$_.LinkProperties linkProperties,
  )
  _onLinkPropertiesChanged;
  final bool onLinkPropertiesChanged$async;
  final void Function(network$_.Network network, int i) _onLosing;
  final bool onLosing$async;
  final void Function(network$_.Network network) _onLost;
  final bool onLost$async;
  final void Function(
    networkcapabilities$_.NetworkCapabilities networkCapabilities,
  )
  _onReserved;
  final bool onReserved$async;
  final void Function() _onUnavailable;
  final bool onUnavailable$async;

  void onAvailable(network$_.Network network) {
    return _onAvailable(network);
  }

  void onBlockedStatusChanged(network$_.Network network, bool z) {
    return _onBlockedStatusChanged(network, z);
  }

  void onCapabilitiesChanged(
    network$_.Network network,
    networkcapabilities$_.NetworkCapabilities networkCapabilities,
  ) {
    return _onCapabilitiesChanged(network, networkCapabilities);
  }

  void onLinkPropertiesChanged(
    network$_.Network network,
    linkproperties$_.LinkProperties linkProperties,
  ) {
    return _onLinkPropertiesChanged(network, linkProperties);
  }

  void onLosing(network$_.Network network, int i) {
    return _onLosing(network, i);
  }

  void onLost(network$_.Network network) {
    return _onLost(network);
  }

  void onReserved(
    networkcapabilities$_.NetworkCapabilities networkCapabilities,
  ) {
    return _onReserved(networkCapabilities);
  }

  void onUnavailable() {
    return _onUnavailable();
  }
}

final class $JConnectivityManager$JNetworkCallback$NullableType$
    extends jni$_.JType<JConnectivityManager$JNetworkCallback?> {
  @jni$_.internal
  const $JConnectivityManager$JNetworkCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity_manager/JConnectivityManager$JNetworkCallback;';

  @jni$_.internal
  @core$_.override
  JConnectivityManager$JNetworkCallback? fromReference(
    jni$_.JReference reference,
  ) => reference.isNull
      ? null
      : JConnectivityManager$JNetworkCallback.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JConnectivityManager$JNetworkCallback?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode =>
      ($JConnectivityManager$JNetworkCallback$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($JConnectivityManager$JNetworkCallback$NullableType$) &&
        other is $JConnectivityManager$JNetworkCallback$NullableType$;
  }
}

final class $JConnectivityManager$JNetworkCallback$Type$
    extends jni$_.JType<JConnectivityManager$JNetworkCallback> {
  @jni$_.internal
  const $JConnectivityManager$JNetworkCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity_manager/JConnectivityManager$JNetworkCallback;';

  @jni$_.internal
  @core$_.override
  JConnectivityManager$JNetworkCallback fromReference(
    jni$_.JReference reference,
  ) => JConnectivityManager$JNetworkCallback.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JConnectivityManager$JNetworkCallback?> get nullableType =>
      const $JConnectivityManager$JNetworkCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JConnectivityManager$JNetworkCallback$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($JConnectivityManager$JNetworkCallback$Type$) &&
        other is $JConnectivityManager$JNetworkCallback$Type$;
  }
}

/// from: `dev.zeekr.connectivity_manager.JConnectivityManager$JNetworkCallbackImpl`
class JConnectivityManager$JNetworkCallbackImpl
    extends connectivitymanager$_.ConnectivityManager$NetworkCallback {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<JConnectivityManager$JNetworkCallbackImpl> $type;

  @jni$_.internal
  JConnectivityManager$JNetworkCallbackImpl.fromReference(
    jni$_.JReference reference,
  ) : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/connectivity_manager/JConnectivityManager$JNetworkCallbackImpl',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JConnectivityManager$JNetworkCallbackImpl?>
  nullableType = $JConnectivityManager$JNetworkCallbackImpl$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JConnectivityManager$JNetworkCallbackImpl> type =
      $JConnectivityManager$JNetworkCallbackImpl$Type$();
  static final _id_new$2 = _class.constructorId(
    r'(Ldev/zeekr/connectivity_manager/JConnectivityManager$JNetworkCallback;)V',
  );

  static final _new$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(dev.zeekr.connectivity_manager.JConnectivityManager$JNetworkCallback jNetworkCallback)`
  /// The returned object must be released after use, by calling the [release] method.
  factory JConnectivityManager$JNetworkCallbackImpl.new$2(
    JConnectivityManager$JNetworkCallback jNetworkCallback,
  ) {
    final _$jNetworkCallback = jNetworkCallback.reference;
    return JConnectivityManager$JNetworkCallbackImpl.fromReference(
      _new$2(
        _class.reference.pointer,
        _id_new$2 as jni$_.JMethodIDPtr,
        _$jNetworkCallback.pointer,
      ).reference,
    );
  }

  static final _id_new$3 = _class.constructorId(
    r'(Ldev/zeekr/connectivity_manager/JConnectivityManager$JNetworkCallback;I)V',
  );

  static final _new$3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public void <init>(dev.zeekr.connectivity_manager.JConnectivityManager$JNetworkCallback jNetworkCallback, int i)`
  /// The returned object must be released after use, by calling the [release] method.
  factory JConnectivityManager$JNetworkCallbackImpl.new$3(
    JConnectivityManager$JNetworkCallback jNetworkCallback,
    int i,
  ) {
    final _$jNetworkCallback = jNetworkCallback.reference;
    return JConnectivityManager$JNetworkCallbackImpl.fromReference(
      _new$3(
        _class.reference.pointer,
        _id_new$3 as jni$_.JMethodIDPtr,
        _$jNetworkCallback.pointer,
        i,
      ).reference,
    );
  }

  static final _id_onAvailable = _class.instanceMethodId(
    r'onAvailable',
    r'(Landroid/net/Network;)V',
  );

  static final _onAvailable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onAvailable(network: android.net.Network): kotlin.Unit`
  void onAvailable(network$_.Network network) {
    final _$network = network.reference;
    _onAvailable(
      reference.pointer,
      _id_onAvailable as jni$_.JMethodIDPtr,
      _$network.pointer,
    ).check();
  }

  static final _id_onBlockedStatusChanged = _class.instanceMethodId(
    r'onBlockedStatusChanged',
    r'(Landroid/net/Network;Z)V',
  );

  static final _onBlockedStatusChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public fun onBlockedStatusChanged(network: android.net.Network, blocked: kotlin.Boolean): kotlin.Unit`
  void onBlockedStatusChanged(network$_.Network network, bool z) {
    final _$network = network.reference;
    _onBlockedStatusChanged(
      reference.pointer,
      _id_onBlockedStatusChanged as jni$_.JMethodIDPtr,
      _$network.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_onCapabilitiesChanged = _class.instanceMethodId(
    r'onCapabilitiesChanged',
    r'(Landroid/net/Network;Landroid/net/NetworkCapabilities;)V',
  );

  static final _onCapabilitiesChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onCapabilitiesChanged(network: android.net.Network, networkCapabilities: android.net.NetworkCapabilities): kotlin.Unit`
  void onCapabilitiesChanged(
    network$_.Network network,
    networkcapabilities$_.NetworkCapabilities networkCapabilities,
  ) {
    final _$network = network.reference;
    final _$networkCapabilities = networkCapabilities.reference;
    _onCapabilitiesChanged(
      reference.pointer,
      _id_onCapabilitiesChanged as jni$_.JMethodIDPtr,
      _$network.pointer,
      _$networkCapabilities.pointer,
    ).check();
  }

  static final _id_onLinkPropertiesChanged = _class.instanceMethodId(
    r'onLinkPropertiesChanged',
    r'(Landroid/net/Network;Landroid/net/LinkProperties;)V',
  );

  static final _onLinkPropertiesChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onLinkPropertiesChanged(network: android.net.Network, linkProperties: android.net.LinkProperties): kotlin.Unit`
  void onLinkPropertiesChanged(
    network$_.Network network,
    linkproperties$_.LinkProperties linkProperties,
  ) {
    final _$network = network.reference;
    final _$linkProperties = linkProperties.reference;
    _onLinkPropertiesChanged(
      reference.pointer,
      _id_onLinkPropertiesChanged as jni$_.JMethodIDPtr,
      _$network.pointer,
      _$linkProperties.pointer,
    ).check();
  }

  static final _id_onLosing = _class.instanceMethodId(
    r'onLosing',
    r'(Landroid/net/Network;I)V',
  );

  static final _onLosing =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public fun onLosing(network: android.net.Network, maxMsToLive: kotlin.Int): kotlin.Unit`
  void onLosing(network$_.Network network, int i) {
    final _$network = network.reference;
    _onLosing(
      reference.pointer,
      _id_onLosing as jni$_.JMethodIDPtr,
      _$network.pointer,
      i,
    ).check();
  }

  static final _id_onLost = _class.instanceMethodId(
    r'onLost',
    r'(Landroid/net/Network;)V',
  );

  static final _onLost =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onLost(network: android.net.Network): kotlin.Unit`
  void onLost(network$_.Network network) {
    final _$network = network.reference;
    _onLost(
      reference.pointer,
      _id_onLost as jni$_.JMethodIDPtr,
      _$network.pointer,
    ).check();
  }

  static final _id_onReserved = _class.instanceMethodId(
    r'onReserved',
    r'(Landroid/net/NetworkCapabilities;)V',
  );

  static final _onReserved =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onReserved(networkCapabilities: android.net.NetworkCapabilities): kotlin.Unit`
  void onReserved(
    networkcapabilities$_.NetworkCapabilities networkCapabilities,
  ) {
    final _$networkCapabilities = networkCapabilities.reference;
    _onReserved(
      reference.pointer,
      _id_onReserved as jni$_.JMethodIDPtr,
      _$networkCapabilities.pointer,
    ).check();
  }

  static final _id_onUnavailable = _class.instanceMethodId(
    r'onUnavailable',
    r'()V',
  );

  static final _onUnavailable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun onUnavailable(): kotlin.Unit`
  void onUnavailable() {
    _onUnavailable(
      reference.pointer,
      _id_onUnavailable as jni$_.JMethodIDPtr,
    ).check();
  }
}

final class $JConnectivityManager$JNetworkCallbackImpl$NullableType$
    extends jni$_.JType<JConnectivityManager$JNetworkCallbackImpl?> {
  @jni$_.internal
  const $JConnectivityManager$JNetworkCallbackImpl$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity_manager/JConnectivityManager$JNetworkCallbackImpl;';

  @jni$_.internal
  @core$_.override
  JConnectivityManager$JNetworkCallbackImpl? fromReference(
    jni$_.JReference reference,
  ) => reference.isNull
      ? null
      : JConnectivityManager$JNetworkCallbackImpl.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType =>
      const connectivitymanager$_.$ConnectivityManager$NetworkCallback$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JConnectivityManager$JNetworkCallbackImpl?> get nullableType =>
      this;

  @jni$_.internal
  @core$_.override
  final superCount = 2;

  @core$_.override
  int get hashCode =>
      ($JConnectivityManager$JNetworkCallbackImpl$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($JConnectivityManager$JNetworkCallbackImpl$NullableType$) &&
        other is $JConnectivityManager$JNetworkCallbackImpl$NullableType$;
  }
}

final class $JConnectivityManager$JNetworkCallbackImpl$Type$
    extends jni$_.JType<JConnectivityManager$JNetworkCallbackImpl> {
  @jni$_.internal
  const $JConnectivityManager$JNetworkCallbackImpl$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity_manager/JConnectivityManager$JNetworkCallbackImpl;';

  @jni$_.internal
  @core$_.override
  JConnectivityManager$JNetworkCallbackImpl fromReference(
    jni$_.JReference reference,
  ) => JConnectivityManager$JNetworkCallbackImpl.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType =>
      const connectivitymanager$_.$ConnectivityManager$NetworkCallback$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JConnectivityManager$JNetworkCallbackImpl?> get nullableType =>
      const $JConnectivityManager$JNetworkCallbackImpl$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 2;

  @core$_.override
  int get hashCode =>
      ($JConnectivityManager$JNetworkCallbackImpl$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType ==
            ($JConnectivityManager$JNetworkCallbackImpl$Type$) &&
        other is $JConnectivityManager$JNetworkCallbackImpl$Type$;
  }
}

/// from: `dev.zeekr.connectivity_manager.JConnectivityManager`
class JConnectivityManager extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<JConnectivityManager> $type;

  @jni$_.internal
  JConnectivityManager.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/zeekr/connectivity_manager/JConnectivityManager',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JConnectivityManager?> nullableType =
      $JConnectivityManager$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<JConnectivityManager> type =
      $JConnectivityManager$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory JConnectivityManager() {
    return JConnectivityManager.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }
}

final class $JConnectivityManager$NullableType$
    extends jni$_.JType<JConnectivityManager?> {
  @jni$_.internal
  const $JConnectivityManager$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity_manager/JConnectivityManager;';

  @jni$_.internal
  @core$_.override
  JConnectivityManager? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : JConnectivityManager.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JConnectivityManager?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JConnectivityManager$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JConnectivityManager$NullableType$) &&
        other is $JConnectivityManager$NullableType$;
  }
}

final class $JConnectivityManager$Type$
    extends jni$_.JType<JConnectivityManager> {
  @jni$_.internal
  const $JConnectivityManager$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/zeekr/connectivity_manager/JConnectivityManager;';

  @jni$_.internal
  @core$_.override
  JConnectivityManager fromReference(jni$_.JReference reference) =>
      JConnectivityManager.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<JConnectivityManager?> get nullableType =>
      const $JConnectivityManager$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($JConnectivityManager$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($JConnectivityManager$Type$) &&
        other is $JConnectivityManager$Type$;
  }
}
